{
 "title": "API Metrics Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{}[$__interval])"
    }
   ]
  },
  {
   "title": "No Of Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "process_num_threads{}" }
   ]
  },
  {
   "title": "Process Virtual Memory Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "process_virtual_memory_bytes{}" }
   ]
  },
  {
   "title": "HealthChecks for DataBase",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "healthcheck_sqlserver", "legendFormat": "__auto" }
   ]
  }
 ]
}