name: Manual Delivery and Test Prometheus

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Run container from GHCR image
      run: |
        docker run -d -p 5000:80 --name cliente-api ghcr.io/${{ github.repository }}:latest
        sleep 10  # espera para que levante el contenedor

    - name: Check Prometheus metric
      run: |
        response=$(curl -s http://localhost:5000/health-metrics)
        echo "$response"

    - name: Stop container
      if: always()
      run: docker stop cliente-api && docker rm cliente-api
