name: Manual Delivery & Prometheus Test

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image from GHCR
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/clienteapi-salas:latest

      - name: Run container from image
        run: |
          docker run -d --rm -p 5000:5000 --name clienteapi ghcr.io/${{ github.repository_owner }}/clienteapi-salas:latest
          sleep 10  # espera a que el contenedor se levante

      - name: Get Prometheus metric
        run: |
          curl http://localhost:5000/metrics | grep -i 'healthcheck' || echo "No healthcheck metric found"

      - name: Stop container
        if: always()
        run: docker stop clienteapi
